title = "Tribe Ties: Building Strength Through Shared Struggles"
baseURL = "https://tribeties.github.io"
languageCode = "en-us"
theme = ["github.com/theNewDynamic/gohugo-theme-ananke"]


DefaultContentLanguage = "en"
SectionPagesMenu = "main"
Paginate = 4 # this is set low for demonstrating with dummy content. Set to a higher number
googleAnalytics = "G-P8BT5RHBNW"
enableRobotsTXT = true

[languages]
  [languages.en]
    title = "TribeTies"
    weight = 1
    contentDir = "content/en"
    # languageDirection = 'rtl' for Right-To-Left languages

[sitemap]
  changefreq = "monthly"
  priority = 0.5
  filename = "sitemap.xml"

[params]
  text_color = ""
  author = ""
  favicon = ""
  site_logo = ""
  description = "Building Strength Through Shared Struggles"
  # choose a background color from any on this page: https://tachyons.io/docs/themes/skins/ and preface it with "bg-"
  background_color_class = "bg-dark-blue"
  recent_posts_number = 3

[[params.ananke_socials]]
name = "twitter"
url = "https://twitter.com/GoHugoIO"
